description = "Base builder for Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/pack:22-build"
run-image = "heroku/pack:22"

[lifecycle]
version = "0.13.5"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:82e235e8c4e5d6d9e0e1e3ba59d8114871565fb2b7df63bcef48d67ecacc09e6"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-scala-buildpack@sha256:02a26d364465a567782806effa2afbf4b992a1e15453bb8e62c5da27118dc7e6"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:a27030592f648d5ef32fe9bcbfe326d435698a748b8fa17b1d43a23fea27ec51"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack@sha256:3eeb3773cdbd29d4fb0d578f7781fe8c525de73593480e2740b7143262e5bef5"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:0.6.2"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.3.1&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack@sha256:15c9702d44be12ec9238fefa912f504013cc0804812e49987ed4bccc6412d6d6"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:04c06bf8b9cea7bd30423a1208e2808119d376372bf38047f6969b0f90419936"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.1.3"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.92"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.8.1"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.29"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.5.1"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.3.16"
