description = "Base builder for Heroku-18 stack, based on ubuntu:18.04 base image"

[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.11.4"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:1ee76637ef8fd4836356a22956b2afe2cd8313a54c21eac2dba875a396c23042"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-scala-buildpack@sha256:39ad34bcc1766cdff4f2a4d5e88931a2f2678f5605bd56f1b6fc551f40fba70f"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:78b246c129f07bfb72b57c16643880d3ad2c4836fdbce80598342aa5d2250c23"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/v222/heroku-buildpack-ruby-v222.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:0.6.2"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.3.1&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack@sha256:b43e71d5338657097582cd48ba27fb0970ace81e08ac25dcf9bbd2659b9f8b14"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:0d27e889a1e23f7cdd7a36a6d36f6547cac1a524694b0a98536ee62f659a7fbd"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.90"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.6.2"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.18"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.3.6"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.3.11"
