[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.9.1"

[[buildpacks]]
  id = "heroku/maven"
  uri = "https://github.com/heroku/heroku-buildpack-java/releases/download/cnb/heroku-buildpack-maven.tgz"

[[buildpacks]]
  id = "heroku/jvm"
  uri = "https://github.com/heroku/heroku-buildpack-jvm-common/releases/download/v106/heroku-jvm-common-cnb-v106.tgz"

[[buildpacks]]
  id = "heroku/java"
  uri = "buildpacks/heroku_java"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/v218/heroku-buildpack-ruby-v218.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "https://github.com/heroku/procfile-cnb/releases/download/v0.5/procfile-cnb-v0.5.tgz"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.2&name=Python"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle?version=0.2&name=Gradle"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.2&name=Scala"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.2&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.2&name=Go"

[[buildpacks]]
  id = "heroku/nodejs-engine"
  uri = "https://github.com/heroku/nodejs-engine-buildpack/releases/download/v0.5.0/nodejs-engine-buildpack-v0.5.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-npm"
  uri = "https://github.com/heroku/nodejs-npm-buildpack/releases/download/v0.3.0/nodejs-npm-buildpack-v0.3.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-yarn"
  uri = "https://github.com/heroku/nodejs-yarn-buildpack/releases/download/v0.0.1/nodejs-yarn-buildpack-v0.0.1.tgz"

[[buildpacks]]
  id = "heroku/nodejs-typescript"
  uri = "https://github.com/heroku/nodejs-typescript-buildpack/releases/download/v0.0.2/nodejs-typescript-buildpack-v0.0.2.tgz"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "buildpacks/heroku_nodejs"

[[buildpacks]]
  id = "salesforce/nodejs-fn"
  uri = "https://github.com/forcedotcom/nodejs-sf-fx-buildpack/releases/download/v2.0.1/nodejs-sf-fx-buildpack-v2.0.1.tgz"

[[buildpacks]]
  id = "projectriff/streaming-http-adapter"
  image = "gcr.io/projectriff/streaming-http-adapter:0.1.3"

[[buildpacks]]
  id = "projectriff/node-function"
  image = "gcr.io/projectriff/node-function:0.6.1"

[[buildpacks]]
  id = "evergreen/fn"
  uri = "buildpacks/evergreen_fn"

[[order]]
  [[order.group]]
    id = "heroku/ruby"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"

[[order]]
  [[order.group]]
    id = "heroku/scala"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "evergreen/fn"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
