description = "Base builder for Heroku-20 stack, based on ubuntu:20.04 base image"

[stack]
id = "heroku-20"
build-image = "heroku/pack:20-build"
run-image = "heroku/pack:20"

[lifecycle]
version = "0.14.0"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:82e235e8c4e5d6d9e0e1e3ba59d8114871565fb2b7df63bcef48d67ecacc09e6"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-scala-buildpack@sha256:02a26d364465a567782806effa2afbf4b992a1e15453bb8e62c5da27118dc7e6"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:a27030592f648d5ef32fe9bcbfe326d435698a748b8fa17b1d43a23fea27ec51"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack@sha256:3eeb3773cdbd29d4fb0d578f7781fe8c525de73593480e2740b7143262e5bef5"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:1.0.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.3.1&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack@sha256:59a86f245b6e6f8e530538e44e8459aa6b7f2541ef78cd4bcf9a90bc09e28519"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:b7298bd863b09bd6b0006250532a92190c24638f47ad3cfd531d9b936abd137a"


[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.1.3"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.92"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.9.0"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.29"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.5.2"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.3.16"
