[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
uri = "lifecycle.tgz"

[[buildpacks]]
  id = "heroku/java"
  uri = "https://github.com/heroku/java-buildpack/releases/download/v0.14/java-buildpack-v0.14.tgz"

 [[buildpacks]]
   id = "heroku/ruby"
   uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/cnb-alpha/ruby-buildpack-vCNB-alpha.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "https://github.com/heroku/procfile-cnb/releases/download/v0.3/procfile-cnb-v0.3.tgz"

[[buildpacks]]
  id = "heroku/python"
  uri = "buildpacks/python"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "buildpacks/gradle"

[[buildpacks]]
  id = "heroku/php"
  uri = "buildpacks/php"

[[buildpacks]]
  id = "heroku/go"
  uri = "buildpacks/go"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "buildpacks/nodejs"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "v0.0.5.0.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.14"

[[order]]
  [[order.group]]
    id = "heroku/gradle"
    version = "v0.0.5.0.2"

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "v0.0.5.0.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "v0.0.5.0.2"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "v0.0.5.0.2"
