[stack]
id = "heroku-20"
build-image = "heroku/pack:20-build"
run-image = "heroku/pack:20"

[lifecycle]
version = "0.9.3"

[[buildpacks]]
  id = "heroku/maven"
  uri = "https://github.com/heroku/heroku-buildpack-java/releases/download/cnb-0.1/heroku-buildpack-maven.tgz"

[[buildpacks]]
  id = "heroku/jvm"
  uri = "https://github.com/heroku/heroku-buildpack-jvm-common/releases/download/v110-cnb/heroku-jvm-common-cnb-v110-cnb.tgz"

[[buildpacks]]
  id = "heroku/java"
  uri = "buildpacks/heroku_java"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/v222/heroku-buildpack-ruby-v222.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "https://github.com/heroku/procfile-cnb/releases/download/v0.6/procfile-cnb-v0.6.tgz"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3&name=Python"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle?version=0.3&name=Gradle"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.3&name=Scala"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.3&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3&name=Go"

[[buildpacks]]
  id = "heroku/nodejs-engine"
  uri = "https://github.com/heroku/nodejs-engine-buildpack/releases/download/v0.7.0/nodejs-engine-buildpack-v0.7.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-npm"
  uri = "https://github.com/heroku/nodejs-npm-buildpack/releases/download/v0.4.0/nodejs-npm-buildpack-v0.4.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-yarn"
  uri = "https://github.com/heroku/nodejs-yarn-buildpack/releases/download/v0.1.0/nodejs-yarn-buildpack-v0.1.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs-typescript"
  uri = "https://github.com/heroku/nodejs-typescript-buildpack/releases/download/v0.2.0/nodejs-typescript-buildpack-v0.2.0.tgz"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "buildpacks/heroku_nodejs"

[[order]]
  [[order.group]]
    id = "heroku/ruby"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"

[[order]]
  [[order.group]]
    id = "heroku/scala"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"

  [[order.group]]
    id = "heroku/procfile"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
