[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.4.0"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "buildpacks/nodejs"

[[buildpacks]]
  id = "heroku/node-function"
  uri = "https://github.com/heroku/node-function-buildpack/releases/download/v0.4.3/node-function-buildpack-v0.4.3.tgz"

[[buildpacks]]
  id = "heroku/java"
  uri = "https://github.com/heroku/java-buildpack/releases/download/v0.14/java-buildpack-v0.14.tgz"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "https://github.com/heroku/java-function-buildpack/releases/download/v0.2.1/java-function-buildpack-v0.2.1.tgz"

[[groups]]
  # node functions
  buildpacks = [
    { id = "heroku/nodejs", version = "v0.0.5.0.2" },
    { id = "heroku/node-function", version = "0.4.3" },
  ]

[[groups]]
  # java functions
  buildpacks = [
    { id = "heroku/java", version = "0.14" },
    { id = "heroku/java-function", version = "0.2.1" },
  ]
