[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.3.0"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "buildpacks/nodejs"

[[buildpacks]]
  id = "heroku/node-function"
  uri = "https://github.com/heroku/node-function-buildpack/releases/download/v0.4.2/node-function-buildpack-v0.4.2.tgz"

[[buildpacks]]
  id = "heroku/java"
  uri = "https://github.com/heroku/java-buildpack/releases/download/v0.13/java-buildpack-v0.13.tgz"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "https://github.com/heroku/java-function-buildpack/releases/download/v0.2.0/java-function-buildpack-v0.2.0.tgz"

[[groups]]
  # node functions
  buildpacks = [
    { id = "heroku/nodejs", version = "v0.0.5.0.1" },
    { id = "heroku/node-function", version = "0.4.2" },
  ]

[[groups]]
  # java functions
  buildpacks = [
    { id = "heroku/java", version = "0.13" },
    { id = "heroku/java-function", version = "0.2.0" },
  ]
