version: 2.1
jobs:
  clone:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project
  create-image:
    parameters:
      dockerfile:
        description: "Dockerfile to build"
        type: string
      image_file:
        description: "Local image archive file name"
        type: string
      image_tag:
        description: "Remote image tag name"
        type: string
      target:
        description: "Docker build target"
        type: string
        default: ""
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run: docker build -f << parameters.dockerfile >> --target "<< parameters.target >>" -t << parameters.image_tag >> .
      - run: docker save << parameters.image_tag >> > << parameters.image_file >>
      - save_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-<< parameters.image_file >>
          paths:
            - << parameters.image_file >>
  create-pack-builder:
    parameters:
      builder_toml:
        description: "Builder toml"
        type: string
      image_file:
        description: "Local builder image archive file name"
        type: string
      image_tag:
        description: "Remote builder image name"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-buildpacks-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-build.tar
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-run.tar
      - setup_remote_docker
      - run: docker pull gcr.io/projectriff/streaming-http-adapter:0.1.3
      - run: docker pull gcr.io/projectriff/node-function:0.6.1
      - run: docker load < pack-18-build.tar
      - run: docker load < pack-18-run.tar
      - run: pack create-builder << parameters.image_tag >> --builder-config << parameters.builder_toml >> --no-pull
      - run: docker save << parameters.image_tag >> > << parameters.image_file >>
      - save_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-<< parameters.image_file >>
          paths:
            - << parameters.image_file >>
  test-getting-started-guide:
    parameters:
      language:
        description: "Language"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - run: git clone https://github.com/heroku/<< parameters.language >>-getting-started.git getting_started
      - setup_remote_docker
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-build.tar
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-run.tar
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-buildpacks-18.tar
      - run: docker load < pack-18-build.tar
      - run: docker load < pack-18-run.tar
      - run: docker load < buildpacks-18.tar
      - run: pack build pack-getting-started --path getting_started --builder heroku/buildpacks:18 --no-pull
  test-typescript-getting-started-guide:
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - run: git clone https://github.com/danielleadams/typescript-getting-started.git getting_started
      - setup_remote_docker
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-build.tar
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-run.tar
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-buildpacks-18.tar
      - run: docker load < pack-18-build.tar
      - run: docker load < pack-18-run.tar
      - run: docker load < buildpacks-18.tar
      - run: pack build pack-getting-started --path getting_started --builder heroku/buildpacks:18 --no-pull
  test-evergreen-canary:
    parameters:
      url:
        description: "Evergreen canaries github repo"
        type: string
      path:
        description: "Build path"
        type: string
      fingerprint:
        description: "Github private repo SSH key"
        type: string
      builder_image_tag:
        description: "Builder image tag to use"
        type: "string"
      builder_file_name:
        description: "Builder cached image name"
        type: "string"
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - << parameters.fingerprint >>
      - run: git clone https://github.com/heroku/evergreen-<< parameters.url >>.git evergreen-canary
      - setup_remote_docker
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-build.tar
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-pack-18-run.tar
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-<< parameters.builder_file_name >>
      - run: docker load < pack-18-build.tar
      - run: docker load < pack-18-run.tar
      - run: docker load < << parameters.builder_file_name >>
      - run: pack build pack-evergreen-canary --path evergreen-canary/src/<< parameters.path >> --builder << parameters.builder_image_tag >> --trust-builder --no-pull
  publish-image:
    parameters:
      image_file:
        description: "Name of the local image archive to publish"
        type: string
      image_tag:
        description: "Name of the dockerhub image to publish"
        type: string
      image_tag_alias:
        description: "Name of dockerhub image alias to publish"
        type: string
    docker:
      - image: heroku/pack-runner:latest
    steps:
      - setup_remote_docker
      - run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
      - restore_cache:
          key: v1-image-{{ .Environment.CIRCLE_SHA1 }}-<< parameters.image_file >>
      - run: docker load < << parameters.image_file >>
      - run: docker push << parameters.image_tag >>
      - run: docker tag << parameters.image_tag >> << parameters.image_tag_alias >>
      - run: docker push << parameters.image_tag_alias >>
workflows:
  version: 2
  build-test-publish:
    jobs: &build-test-publish-jobs
      - clone
      - create-image:
          name: create-build-image
          dockerfile: Dockerfile.build
          image_tag: heroku/pack:18-build
          image_file: pack-18-build.tar
          requires:
            - clone
      - create-image:
          name: create-run-image
          dockerfile: Dockerfile.run
          image_tag: heroku/pack:18
          image_file: pack-18-run.tar
          requires:
            - clone
      - create-pack-builder:
          name: create-service-builder
          image_tag: heroku/buildpacks:18
          image_file: buildpacks-18.tar
          builder_toml: builder.toml
          requires:
            - create-run-image
            - create-build-image
      - create-pack-builder:
          name: create-functions-builder
          image_tag: heroku/functions-buildpacks:18
          image_file: functions-buildpacks-18.tar
          builder_toml: functions-builder.toml
          requires:
            - create-run-image
            - create-build-image
      - test-getting-started-guide:
          language: go
          name: test-go
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: java
          name: test-java
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: node-js
          name: test-node-js
          requires:
            - create-service-builder
      - test-typescript-getting-started-guide:
          name: test-typescript
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: php
          name: test-php
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: Python
          name: test-python
          requires:
            - create-service-builder
      - test-getting-started-guide:
          language: Ruby
          name: test-ruby
          requires:
            - create-service-builder
      - test-evergreen-canary:
          name: test-canary-https-invocation-functions-builder
          url: canary-https-invocation
          path: hello-function
          fingerprint: "5f:51:54:de:aa:c6:91:98:3e:e9:b2:a3:94:e7:05:6d"
          builder_image_tag: "heroku/functions-buildpacks:18"
          builder_file_name: functions-buildpacks-18.tar
          requires: 
            - create-functions-builder
      - test-evergreen-canary:
          name: test-canary-https-invocation-builder
          url: canary-https-invocation
          path: hello-function
          fingerprint: "5f:51:54:de:aa:c6:91:98:3e:e9:b2:a3:94:e7:05:6d"
          builder_image_tag: "heroku/buildpacks:18"
          builder_file_name: buildpacks-18.tar
          requires: 
            - create-builder
      - test-evergreen-canary:
          name: test-canary-logs-cli-functions-builder
          url: canary-logs-cli
          path: salesforce/functions/ExampleFunction
          fingerprint: "c1:1d:be:7b:33:56:47:56:8a:84:55:15:9f:7c:5e:1c"
          builder_image_tag: "heroku/functions-buildpacks:18"
          builder_file_name: functions-buildpacks-18.tar
          requires: 
            - create-functions-builder
      - test-evergreen-canary:
          name: test-canary-logs-cli-builder
          url: canary-logs-cli
          path: salesforce/functions/ExampleFunction
          fingerprint: "c1:1d:be:7b:33:56:47:56:8a:84:55:15:9f:7c:5e:1c"
          builder_image_tag: "heroku/buildpacks:18"
          builder_file_name: buildpacks-18.tar
          requires: 
            - create-builder
      - publish-image:
          name: publish-build-stack
          image_file: pack-18-build.tar
          image_tag: heroku/pack:18-build
          image_tag_alias: heroku/pack:18-build
          requires:
            - test-go
            - test-java
            - test-node-js
            - test-ruby
            - test-php
            - test-python
            - test-canary-https-invocation-functions-builder
            - test-canary-https-invocation-builder
            - test-canary-logs-cli-functions-builder
            - test-canary-logs-cli-builder
          filters:
            branches:
              only: master
      - publish-image:
          name: publish-run-stack
          image_file: pack-18-run.tar
          image_tag: heroku/pack:18
          image_tag_alias: heroku/pack:18
          requires:
            - test-go
            - test-java
            - test-node-js
            - test-ruby
            - test-php
            - test-python
            - test-canary-https-invocation-functions-builder
            - test-canary-https-invocation-builder
            - test-canary-logs-cli-functions-builder
            - test-canary-logs-cli-builder
          filters:
            branches:
              only: master
      - publish-image:
          name: publish-service-builder
          image_file: buildpacks-18.tar
          image_tag: heroku/buildpacks:18
          image_tag_alias: heroku/buildpacks:latest
          requires:
            - publish-build-stack
            - publish-run-stack
          filters:
            branches:
              only: master
      - publish-image:
          name: publish-functions-builder
          image_file: functions-buildpacks-18.tar
          image_tag: heroku/functions-buildpacks:18
          image_tag_alias: heroku/functions-buildpacks:latest
          requires:
            - publish-build-stack
            - publish-run-stack
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs: *build-test-publish-jobs
