api = "0.2"

[buildpack]
id = "evergreen/fn"
version = "0.3.0"
name = "Evergreen Function"

[[order]]
  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.5.3"

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.8"
